### ISSUE TITLE
 Constructor sqstat.class.php on line 5

### ISSUE THREAD

**Issue by maravento** [lorf/sqstat#1]
Hi. Error log

In /var/log/apache2/error.log

PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; squidstat has a deprecated constructor in /var/www/html/sqstat/sqstat.class.php on line 5

squid 3.5.12
apache/2.4.18
Ubuntu 16.04.1
kernel 4.4.0-34-generic
php 7.0.9-1

Thanks

**Comment by lorf** [comment]
Thanks!
